function createfigure(X1, YMatrix1, X2, Y1)
%CREATEFIGURE(X1, YMatrix1, X2, Y1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 03-Oct-2021 18:18:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',5);
set(plot1(1),'DisplayName','Ratio: $XLE to $QQQ','LineWidth',0.5);
set(plot1(2),'DisplayName','One New MA');
set(plot1(3),'DisplayName','Four Year MA');

% Create plot
plot(X2,Y1,'DisplayName','Today''s Ratio','LineStyle','--','Color',[0 0 0]);

% Create text
text('Parent',axes1,'HorizontalAlignment','center','FontAngle','italic',...
    'FontSize',36,...
    'FontName','Helvetica Neue',...
    'String',{'Ratio of Investments:','Oil & Gas / Tech'},...
    'Position',[3818.76632302406 0.336654804270463 0]);

% Create text
text('Parent',axes1,'HorizontalAlignment','center','FontSize',18,...
    'String','October 3rd: 0.13',...
    'Position',[6684.9335522313 0.0893038790536701 0]);

% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.0386813186813188 1.56131868131868]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',18,'YTick',[0 0.2 0.4 0.6 0.8 1 1.2 1.4 1.6 1.8 2]);
% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.155399543378993 0.742413043478263 0.222602739726027 0.123913043478261],...
    'Interpreter','none');

% % Create textbox
% annotation(figure1,'textbox',...
%     [0.496575342465752 0.755072463768116 0.381278538812785 0.138130434782609],...
%     'VerticalAlignment','middle',...
%     'String',{'Energy Rotation','2022-2025'},...
%     'LineWidth',1,...
%     'HorizontalAlignment','center',...
%     'FontWeight','bold',...
%     'FontSize',44,...
%     'FontName','Party LET',...
%     'FontAngle','italic',...
%     'FitBoxToText','off',...
%     'EdgeColor','none');

